### PR TITLE
Fix scrolling loop (for updated gocui)

### PR DESCRIPTION
**Pull request by mattroseman**
I noticed that you updated gocui to `1.1` and then reverted it. When I run on the `0.6` version with go `1.20` I can't type or scroll at all, and if I run with go `1.19`, the cursor acts odd when I click in the chat input. So I tried updating gocui myself.

Using gocui `1.1` seemed to work much better for me, except there was an issue where if I scrolled too fast it would wraparound to the beginning of the chat.

If you plan on still updating gocui, I think this fix will stop the scrolling from looping around. IDK if you saw other issues which made you revert the update, though.

### TL;DR
I think there's a race condition with scrolling and how gocui draws the view.
I manually set the view's origin after it gets cleared in `guiwrapper.redraw`, and the problem is fixed.

### Longer Explanation

I think what is happening is the `scroll()` [method](https://github.com/cantclosevim/tdgg/blob/9777c354831579f6f24fda022a7df1fe9c3ef449/ui.go#L465) is calling `redraw()` within the `chat.guiwrapper.Lock()` mutex. But, `redraw()` method is [clearing all chat messages and re-adding them](https://github.com/cantclosevim/tdgg/blob/9777c354831579f6f24fda022a7df1fe9c3ef449/guiwrapper.go#L65), which resets the origin to (0,0).

Normally the origin is corrected by gocui's [MainLoop](https://github.com/awesome-gocui/gocui/blob/384f06fbdddfe41d9ddebbcb58ccb67697246e8c/gui.go#L478) flushing the view, which eventually applies the `Autoscroll` flag and [scrolls to the bottom](https://github.com/awesome-gocui/gocui/blob/384f06fbdddfe41d9ddebbcb58ccb67697246e8c/view.go#L574).

However, if you scroll fast enough, I believe you can get in a second `scroll()` call before gocui's MainLoop gets a chance to flush and correct the Origin. The second scroll scrolls from (0, 0) Origin, and fucks the whole thing up.
That's my theory anyway.

So I just manually set the Origin to the bottom in the `guiwrapper.redraw` method—meaning it's within the `chat.guiwrapper.Lock()` mutex—so if there's a second scroll, it'll work from the right starting place.

### CODE REVIEW

**Comment by cantclosevim** [comment]
I couldn't reproduce this go `1.20` + gocui `0.6` scrolling/typing issue on the latest master, both seem to be working here while using urxvt `9.31` as my terminal emulator. However, I did encounter in this PR the same issue that made me revert gocui from `1.1` to `0.6`: Moving the cursor over a view causes it to be scrolled.

Here's a video demonstrating this, running on the left is the latest master and on the right is this PR:

https://user-images.githubusercontent.com/107156495/224304816-73bc298b-58d2-4343-9ffc-883d8224f99f.mp4

I've decided to also install and test alacritty (another terminal emulator), but I couldn't reproduce the issues we're reporting: Scrolling and typing on the latest master works and the cursor moving issue does not happen either. If I had to guess I would say that these are problems specific to how our different terminals behave.

If we can find a solution to the issues outlined above I'll be happy to merge this PR.

**Comment by mattroseman** [comment]
Damn. I might look into gocui documentation to see if they comment on any weird idiosyncrasies with different terminals.
But it sounds like it might be difficult to set this up to work consistently on the latest versions.
All well, I'll comment here if I find anything.

Also, for reference, I'm using Iterm2.

**Comment by mattroseman** [comment]
OK my guess, which is based solely on browsing around the code and not actually testing anything, is that the issues you and I saw come from the change from `termbox-go` to `tcell` as the underlying library for interfacing with the terminal.

It would seem, from your description, that mouse movements are being misread as scroll wheel events.
[termbox-go code](https://github.com/nsf/termbox-go/blob/71f343b9e47a1bccfd85520a997208d61c78f89f/termbox.go#L369) shows what looks like more robust categorization of mouse events. In other words, I see more if statements :)
[tcell's equivalent code](https://github.com/gdamore/tcell/blob/c951371181bb4b1387d9010b8081590ae6a48152/mouse.go#L85) looks a bit more simplified.

That's my rough guess from poking around in the code at least.
Maybe `tcell` will be updated to be more robust at some point, the repo does seem more incipient than termbox-go.

**Comment by cantclosevim** [comment]
Moving from urxvt to alacritty and merging this as it is not worth it to break compatibility with other terminal emulators and keep an outdated version of `gocui` just to support it.

**Comment by mattroseman** [comment]
I did end up digging into tcell code, and I think I figured out the issue.

I might be wrong; I have an issue and [PR](https://github.com/gdamore/tcell/pull/601) up right now, so we'll see.

I believe this would fix it for urxvt.

**Pull request merged**
